#include<stdio.h>
#include<signal.h>
#include<stdlib.h>
#include<unistd.h>
#include<sys/socket.h>
#include<sys/wait.h>
#include<fcntl.h>
#include<string.h>
#include<sys/time.h>
#include<time.h>
#include<ctype.h>
